version: '3.8'

services:
  postgres-api:
    image: postgres:14.3
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: 'protein-tokenizer'
      POSTGRES_USER: 'tokenizer'
      POSTGRES_PASSWORD: 'tokenizer'
  rabbitmq:
    image: rabbitmq:3.10.5-management
    container_name: rabbit
    ports:
      - '5672:5672'
      - '15672:15672'
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - type: bind
        source: ./prometheus.yml
        target: /etc/prometheus/prometheus.yml
    ports:
      - 9090:9090