name: Deploy frontend

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Add frontend remote origin
              run: git remote add heroku-frontend https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/${{ secrets.HEROKU_FRONTEND_APP_NAME }}.git
            - name: Deploy frontend to Heroku
              run: git push heroku-frontend `git subtree split --prefix applications/frontend main`:refs/heads/main --force