name: Deploy backend

on:
    push:
        branches:
            - main
        paths:
            - "applications/backend/**"
            - "components/queue/**"
            - ".github/workflows/deploy-backend.yml"

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Add backend remote origin
              run: git remote add heroku-backend https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/${{ secrets.HEROKU_BACKEND_APP_NAME }}.git
            - name: Deploy backend to Heroku
              run: |
                git config user.name github-actions
                git config user.email github-actions@github.com
                mv applications/backend/Procfile ./
                mv applications/backend/requirements.txt ./
                git add .
                git commit -a -m "Make buildpack hap hap happy"
                git push heroku-backend main --force