name: Deploy datacollector

on:
    push:
        branches:
            - main
        paths:
            - "applications/datacollector/**"
            - ".github/workflows/deploy-datacollector.yml"

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                fetch-depth: 0
            - name: Add datacollector remote origin
              run: git remote add heroku-collector https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/${{ secrets.HEROKU_COLLECTOR_APP_NAME }}.git
            - name: Deploy datacollector to Heroku
              run: |
                git config user.name github-actions
                git config user.email github-actions@github.com
                echo "uvicorn applications/datacollector/DataCollector:app" > Procfile
                mv applications/datacollector/requirements.txt .
                git add .
                git commit -m "Make buildpack hap hap happy"
                git push heroku-collector main